CATALOG = [
    {
        "slug": "rh-board-assembled",
        "name": "Собранная плата засечки RotorHazard",
        "category": "RotorHazard",
        "price": 8000,
        "old_price": 14000,
        "short_desc": "Готовая собранная и протестированная плата засечки",
    },
    {
        "slug": "rh-pcb",
        "name": "Печатная плата RotorHazard",
        "category": "RotorHazard",
        "price": 1000,
        "old_price": 2000,
        "short_desc": "Голая PCB плата для самостоятельной сборки",
    },
    {
        "slug": "rh-kit",
        "name": "Комплект для сборки RotorHazard",
        "category": "RotorHazard",
        "price": 4000,
        "old_price": 6000,
        "short_desc": "Полный набор компонентов для самостоятельной сборки",
    },
    {
        "slug": "rh-carbon-case",
        "name": "Карбоновый корпус для RotorHazard",
        "category": "RotorHazard",
        "price": 2000,
        "old_price": 3000,
        "short_desc": "Защитный корпус из карбона",
    },
    {
        "slug": "rh-plastic-case",
        "name": "Пластиковый корпус для RotorHazard",
        "category": "RotorHazard",
        "price": 1000,
        "old_price": 2000,
        "short_desc": "Защитный корпус из пластика",
    },
    {
        "slug": "raspberry-pi-5",
        "name": "Raspberry Pi 5 8GB",
        "category": "RotorHazard",
        "price": 9000,
        "old_price": 12000,
        "short_desc": "Мини-компьютер для запуска RotorHazard",
    },
    {
        "slug": "rx5808",
        "name": "Приёмник RX5808 Boscam",
        "category": "RotorHazard",
        "price": 2000,
        "old_price": 3000,
        "short_desc": "Приёмник 5.8 ГГц для одного пилота",
    },
    {
        "slug": "nh-atom",
        "name": "Модуль NuclearHazard Atom",
        "category": "NuclearHazard",
        "price": 3000,
        "old_price": 5000,
        "short_desc": "Компактный модуль засечки",
    },
    {
        "slug": "nh-full",
        "name": "Модуль NuclearHazard",
        "category": "NuclearHazard",
        "price": 12000,
        "old_price": 16000,
        "short_desc": "Полнофункциональный модуль засечки",
    },
    {
        "slug": "rh-turnkey",
        "name": "Комплект «под ключ» RotorHazard",
        "category": "RotorHazard",
        "price": 38500,
        "old_price": 45000,
        "short_desc": "Готовый комплект для клуба или мероприятия",
    },
]
