"""init

Revision ID: 49d664e59a09
Revises: 
Create Date: 2026-04-12 11:00:38.275586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d664e59a09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pilot', 'viewer', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('format', sa.Enum('multigp', 'arrive_and_fly', 'custom', name='eventformat'), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('rotorhazard_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('callsign', sa.String(length=100), nullable=False),
    sa.Column('real_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('timer_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pre_beep_delay_sec', sa.Float(), nullable=False),
    sa.Column('beep_count', sa.Integer(), nullable=False),
    sa.Column('random_delay_min_sec', sa.Float(), nullable=False),
    sa.Column('random_delay_max_sec', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity_mah', sa.Integer(), nullable=True),
    sa.Column('cell_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('drone_name', sa.String(length=200), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('heat_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'done', name='heatstatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('training', 'race', 'heat', name='sessiontype'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', name='crashseverity'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heat_pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('gate_color', sa.String(length=50), nullable=True),
    sa.Column('result_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['heat_id'], ['heats.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'rotorhazard', name='lapsource'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pack_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('cycles_in_session', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['battery_packs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pack_usages')
    op.drop_table('laps')
    op.drop_table('heat_pilots')
    op.drop_table('crashes')
    op.drop_table('sessions')
    op.drop_table('heats')
    op.drop_table('equipment')
    op.drop_table('battery_packs')
    op.drop_table('timer_configs')
    op.drop_table('pilots')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
